// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBplunczMWmP1ooKiNDIaVDObh2DszD8WI',
    appId: '1:28921298414:web:bed8354fc19c32321962ff',
    messagingSenderId: '28921298414',
    projectId: 'simple-login-logout-flutter',
    authDomain: 'simple-login-logout-flutter.firebaseapp.com',
    storageBucket: 'simple-login-logout-flutter.appspot.com',
    measurementId: 'G-R5VMHSWJBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwG8MG0uq3Azln27IeCjdMhqPWpKF1T1I',
    appId: '1:28921298414:android:f4788f26694c75b21962ff',
    messagingSenderId: '28921298414',
    projectId: 'simple-login-logout-flutter',
    storageBucket: 'simple-login-logout-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9EXFFFkLoX4EO8rhRkG6hJFZWCZb8g2U',
    appId: '1:28921298414:ios:136c7bcd87b2299b1962ff',
    messagingSenderId: '28921298414',
    projectId: 'simple-login-logout-flutter',
    storageBucket: 'simple-login-logout-flutter.appspot.com',
    iosClientId: '28921298414-9rf3sbd7cq0srqgva43qmdhs1cjkp2qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );
}
